/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CCiudad;
import Modelo.MBarrio;




/**
 *
 * @author Teresa
 */
public class VBarrio extends javax.swing.JFrame {

    /**
     * Creates new form VProducto
     */
    public VBarrio() {
        initComponents();
    }
    MBarrio modelo = new MBarrio();
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoDescripcion = new javax.swing.JTextField();
        ELIMINAR = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        IMPRIMIR = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        VER = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboCiudad = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        BotonAgregarNacionalidad = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoBuscar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 540));
        setMinimumSize(new java.awt.Dimension(700, 540));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Formulario de Barrios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 200, 20);

        CampoCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo);
        CampoCodigo.setBounds(80, 80, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Ciudad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 160, 50, 40);

        CampoDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(CampoDescripcion);
        CampoDescripcion.setBounds(80, 120, 170, 30);

        ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/eliminar.jpg"))); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.setToolTipText("Eliminar un registro existente");
        getContentPane().add(ELIMINAR);
        ELIMINAR.setBounds(490, 90, 160, 50);

        NUEVO.setText("NUEVO");
        NUEVO.setToolTipText("Cancelar Operacion");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(NUEVO);
        NUEVO.setBounds(490, 140, 160, 50);

        IMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/imprimir.jpg"))); // NOI18N
        IMPRIMIR.setText("IMPRIMIR");
        IMPRIMIR.setToolTipText("Imprimir Listado");
        IMPRIMIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMPRIMIRActionPerformed(evt);
            }
        });
        getContentPane().add(IMPRIMIR);
        IMPRIMIR.setBounds(490, 290, 160, 50);

        GUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/agrega.jpg"))); // NOI18N
        GUARDAR.setText("GUARDAR");
        GUARDAR.setToolTipText("Guardar Registros");
        getContentPane().add(GUARDAR);
        GUARDAR.setBounds(490, 240, 160, 50);

        MODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/modificar1.jpg"))); // NOI18N
        MODIFICAR.setText("MODIFICAR ");
        MODIFICAR.setToolTipText("Modificar un registro existente");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });
        getContentPane().add(MODIFICAR);
        MODIFICAR.setBounds(490, 190, 160, 50);

        VER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/ver.jpg"))); // NOI18N
        VER.setText("VER");
        VER.setToolTipText("Consultar Datos Existentes");
        getContentPane().add(VER);
        VER.setBounds(490, 40, 160, 50);

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR);
        SALIR.setBounds(490, 340, 160, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Codigo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 80, 50, 20);

        ComboCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(ComboCiudad);
        ComboCiudad.setBounds(80, 160, 180, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 110, 70, 40);

        BotonAgregarNacionalidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonAgregarNacionalidad.setText("...");
        BotonAgregarNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNacionalidadActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarNacionalidad);
        BotonAgregarNacionalidad.setBounds(270, 160, 70, 40);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Consulta de Datos");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 0, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Busqueda");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 30, 120, 30);

        CampoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CampoBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(CampoBuscar);
        CampoBuscar.setBounds(140, 30, 270, 30);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaConsulta);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 400, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 220, 480, 200);

        jLabel2.setText("Buscar Ciudad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 140, 68, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void IMPRIMIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMPRIMIRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IMPRIMIRActionPerformed

    private void ComboCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCiudadActionPerformed

    private void BotonAgregarNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNacionalidadActionPerformed
        new CCiudad(new VCiudad()).iniciar();
    }//GEN-LAST:event_BotonAgregarNacionalidadActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
          this.ComboCiudad.setModel(this.modelo.getListaciudades());
    }//GEN-LAST:event_formWindowActivated

    private void CampoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoBuscarKeyReleased

    }//GEN-LAST:event_CampoBuscarKeyReleased

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUEVOActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarNacionalidad;
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField CampoDescripcion;
    public javax.swing.JComboBox ComboCiudad;
    public javax.swing.JButton ELIMINAR;
    public javax.swing.JButton GUARDAR;
    public javax.swing.JButton IMPRIMIR;
    public javax.swing.JButton MODIFICAR;
    public javax.swing.JButton NUEVO;
    public javax.swing.JButton SALIR;
    public javax.swing.JButton VER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
