

package Vista;

import Controlador.CBuscarProductos;
import javax.swing.JOptionPane;



public class VBuscarProductos extends javax.swing.JFrame {
     
     
     
    /** Creates new form VConsultaCliente1 */
    public VBuscarProductos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSeleccionarLugar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        RadioButonNombre = new javax.swing.JRadioButton();
        RadioButonMostrarTodo = new javax.swing.JRadioButton();
        BotonBuscar = new javax.swing.JButton();
        CampoBusca = new javax.swing.JTextField();
        SALIR1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelCampos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_busca = new javax.swing.JTable();
        jPanelConsulta = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        CampoCodProducto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        CampoDescripcion = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CampoFoto = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        CampoCantidad = new javax.swing.JTextField();
        CampoPrecioV = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        BotonSeleccionarLugar.setText("Seleccionar");
        BotonSeleccionarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSeleccionarLugarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSeleccionarLugar);
        BotonSeleccionarLugar.setBounds(570, 480, 140, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);

        RadioButonNombre.setText("Buscar por Nombre:");
        RadioButonNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButonNombreActionPerformed(evt);
            }
        });
        jPanel2.add(RadioButonNombre);
        RadioButonNombre.setBounds(10, 23, 230, 30);

        RadioButonMostrarTodo.setText("Mostrar todos los registros");
        RadioButonMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButonMostrarTodoActionPerformed(evt);
            }
        });
        jPanel2.add(RadioButonMostrarTodo);
        RadioButonMostrarTodo.setBounds(440, 20, 230, 30);

        BotonBuscar.setText("BUSCAR");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(BotonBuscar);
        BotonBuscar.setBounds(690, 20, 73, 60);
        jPanel2.add(CampoBusca);
        CampoBusca.setBounds(250, 20, 160, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 40, 820, 130);

        SALIR1.setText("SALIR");
        SALIR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIR1ActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR1);
        SALIR1.setBounds(710, 480, 140, 40);

        jLabel1.setFont(new java.awt.Font("Aparajita", 1, 36)); // NOI18N
        jLabel1.setText("Buscar Productos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 10, 250, 30);

        jPanelCampos.setLayout(null);

        tabla_busca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_busca);

        jPanelCampos.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 790, 150);

        jTabbedPane1.addTab("Consulta Datos", jPanelCampos);

        jPanelConsulta.setLayout(null);

        jLabel14.setText("Codigo Item:");
        jPanelConsulta.add(jLabel14);
        jLabel14.setBounds(10, 20, 90, 20);

        CampoCodProducto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoCodProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodProductoActionPerformed(evt);
            }
        });
        jPanelConsulta.add(CampoCodProducto);
        CampoCodProducto.setBounds(100, 20, 90, 20);

        jLabel15.setText("Descripción:");
        jPanelConsulta.add(jLabel15);
        jLabel15.setBounds(210, 20, 90, 14);

        CampoDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanelConsulta.add(CampoDescripcion);
        CampoDescripcion.setBounds(280, 20, 260, 20);

        jLabel17.setText("Imagen:");
        jPanelConsulta.add(jLabel17);
        jLabel17.setBounds(550, 80, 50, 20);

        CampoFoto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanelConsulta.add(CampoFoto);
        CampoFoto.setBounds(620, 80, 150, 20);

        jLabel21.setText("Cantidad");
        jPanelConsulta.add(jLabel21);
        jLabel21.setBounds(30, 110, 90, 20);

        CampoCantidad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanelConsulta.add(CampoCantidad);
        CampoCantidad.setBounds(100, 110, 90, 20);

        CampoPrecioV.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanelConsulta.add(CampoPrecioV);
        CampoPrecioV.setBounds(370, 110, 150, 20);

        jLabel23.setText("Precio Venta");
        jPanelConsulta.add(jLabel23);
        jLabel23.setBounds(290, 110, 60, 20);

        jTabbedPane1.addTab("", jPanelConsulta);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 180, 820, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
     static String codProducto="";
     static String Descripcion="";   
     static String Foto=""; 
      static String Cantidad=""; 
       static String PrecioVenta=""; 
    private void BotonSeleccionarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSeleccionarLugarActionPerformed
            codProducto=this.CampoCodProducto.getText();
            Descripcion=this.CampoDescripcion.getText();           
            
            Foto=this.CampoFoto.getText();
            Cantidad=this.CampoCantidad.getText();
            PrecioVenta=this.CampoPrecioV.getText();
       
                      
        JOptionPane.showMessageDialog(null, "Registro Seleccionado");
        this.dispose();
}//GEN-LAST:event_BotonSeleccionarLugarActionPerformed

    private void RadioButonNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButonNombreActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_RadioButonNombreActionPerformed

    private void RadioButonMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButonMostrarTodoActionPerformed

    }//GEN-LAST:event_RadioButonMostrarTodoActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed

    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void SALIR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIR1ActionPerformed
        dispose();
    }//GEN-LAST:event_SALIR1ActionPerformed

    private void CampoCodProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
               new CBuscarProductos(new VBuscarProductos()).iniciar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonBuscar;
    public javax.swing.JButton BotonSeleccionarLugar;
    public javax.swing.JTextField CampoBusca;
    public javax.swing.JTextField CampoCantidad;
    public javax.swing.JTextField CampoCodProducto;
    public javax.swing.JTextField CampoDescripcion;
    public javax.swing.JTextField CampoFoto;
    public javax.swing.JTextField CampoPrecioV;
    public javax.swing.JRadioButton RadioButonMostrarTodo;
    public javax.swing.JRadioButton RadioButonNombre;
    public javax.swing.JButton SALIR1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCampos;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tabla_busca;
    // End of variables declaration//GEN-END:variables

}
