/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author user
 */
public class VEntidadesEmisoras extends javax.swing.JFrame {

    /**
     * Creates new form VNacionalidad
     */
    public VEntidadesEmisoras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CampoDireccion = new javax.swing.JTextField();
        CampoCodigo = new javax.swing.JTextField();
        BotonEliminar = new javax.swing.JButton();
        BotonVer = new javax.swing.JButton();
        BotonNuevo = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonImprimir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CampoRazonSocial = new javax.swing.JTextField();
        CampoRuc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CampoTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Entidades Emisoras");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 30, 180, 40);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaConsulta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 300, 650, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Lista de Consulta de Entidades");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 250, 270, 40);

        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 110, 70, 30);

        jLabel4.setText("Codigo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 50, 20);

        CampoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(CampoDireccion);
        CampoDireccion.setBounds(340, 110, 160, 30);

        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo);
        CampoCodigo.setBounds(100, 110, 130, 30);

        BotonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/eliminar.jpg"))); // NOI18N
        BotonEliminar.setText("ELIMINAR");
        getContentPane().add(BotonEliminar);
        BotonEliminar.setBounds(700, 280, 150, 60);

        BotonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/ver.jpg"))); // NOI18N
        BotonVer.setText("VER");
        getContentPane().add(BotonVer);
        BotonVer.setBounds(700, 40, 150, 60);

        BotonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/nuevoReg.jpg"))); // NOI18N
        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonNuevo);
        BotonNuevo.setBounds(700, 100, 150, 60);

        BotonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/agrega.jpg"))); // NOI18N
        BotonGuardar.setText("GUARDAR");
        getContentPane().add(BotonGuardar);
        BotonGuardar.setBounds(700, 160, 150, 60);

        BotonModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/modificar1.jpg"))); // NOI18N
        BotonModificar.setText("MODIFICAR");
        getContentPane().add(BotonModificar);
        BotonModificar.setBounds(700, 220, 150, 60);

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/salir2.jpg"))); // NOI18N
        BotonSalir.setText("SALIR");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir);
        BotonSalir.setBounds(700, 400, 150, 60);

        BotonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/imprimir.jpg"))); // NOI18N
        BotonImprimir.setText("IMPRIMIR");
        getContentPane().add(BotonImprimir);
        BotonImprimir.setBounds(700, 340, 150, 60);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 160, 70, 30);

        jLabel6.setText("RazonSocial");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 150, 70, 30);

        jLabel7.setText("Ruc");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 70, 30);

        CampoRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRazonSocialActionPerformed(evt);
            }
        });
        getContentPane().add(CampoRazonSocial);
        CampoRazonSocial.setBounds(100, 150, 160, 30);

        CampoRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRucActionPerformed(evt);
            }
        });
        getContentPane().add(CampoRuc);
        CampoRuc.setBounds(100, 190, 160, 30);

        jLabel8.setText("Telefono");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 150, 70, 30);

        CampoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoTelefono);
        CampoTelefono.setBounds(340, 150, 160, 30);

        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 190, 70, 30);

        CampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CampoEmail);
        CampoEmail.setBounds(340, 190, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDireccionActionPerformed

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void CampoRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoRazonSocialActionPerformed

    private void CampoRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoRucActionPerformed

    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNuevoActionPerformed

    private void CampoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefonoActionPerformed

    private void CampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VEntidadesEmisoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VEntidadesEmisoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VEntidadesEmisoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VEntidadesEmisoras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VEntidadesEmisoras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonEliminar;
    public javax.swing.JButton BotonGuardar;
    public javax.swing.JButton BotonImprimir;
    public javax.swing.JButton BotonModificar;
    public javax.swing.JButton BotonNuevo;
    public javax.swing.JButton BotonSalir;
    public javax.swing.JButton BotonVer;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField CampoDireccion;
    public javax.swing.JTextField CampoEmail;
    public javax.swing.JTextField CampoRazonSocial;
    public javax.swing.JTextField CampoRuc;
    public javax.swing.JTextField CampoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
