/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CBarrio;
import Controlador.CColor;
import Controlador.CMarca;
import Controlador.CMedida;
import Controlador.CModelo;
import Controlador.CNacionalidad;
import Controlador.CTipoEquipo;
import Modelo.MCliente;
import Modelo.MEquipo;





/**
 *
 * @author Teresa
 */
public class VEquipo extends javax.swing.JFrame {
     
    /**
     * Creates new form VProducto
     */
    public VEquipo() {
        initComponents();
    }
    MEquipo modelo = new MEquipo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoDescripcion = new javax.swing.JTextField();
        ELIMINAR = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        IMPRIMIR = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        VER = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboTipoEquipo = new javax.swing.JComboBox();
        BotonAgregarNacionalidad = new javax.swing.JButton();
        ComboMarca = new javax.swing.JComboBox();
        BotonAgregarBarrio = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ComboMedida = new javax.swing.JComboBox();
        BotonAgregarNacionalidad1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ComboColor = new javax.swing.JComboBox();
        BotonAgregarNacionalidad2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ComboModelo = new javax.swing.JComboBox();
        BotonAgregarNacionalidad3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaConsulta.setToolTipText("Consulta de Registros Existentes");
        tablaConsulta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaConsulta.setName(""); // NOI18N
        jScrollPane1.setViewportView(tablaConsulta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 510, 800, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Consulta Equipo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 460, 220, 30);

        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 50, 20);

        CampoCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo);
        CampoCodigo.setBounds(100, 110, 120, 30);

        jLabel4.setText("Observacion");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 350, 80, 30);

        CampoDescripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(CampoDescripcion);
        CampoDescripcion.setBounds(100, 350, 230, 30);

        ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/eliminar.jpg"))); // NOI18N
        ELIMINAR.setText("ELIMINAR ");
        ELIMINAR.setToolTipText("Eliminar un registro existente");
        getContentPane().add(ELIMINAR);
        ELIMINAR.setBounds(430, 290, 150, 50);

        NUEVO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aurelia\\Desktop\\SystemSolution\\src\\imagen2\\nuevoReg.jpg")); // NOI18N
        NUEVO.setText("NUEVO  ");
        NUEVO.setToolTipText("Cancelar Operacion");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(NUEVO);
        NUEVO.setBounds(430, 140, 150, 50);

        IMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/imprimir.jpg"))); // NOI18N
        IMPRIMIR.setText("IMPRIMIR");
        IMPRIMIR.setToolTipText("Imprimir Listado");
        getContentPane().add(IMPRIMIR);
        IMPRIMIR.setBounds(430, 340, 150, 50);

        GUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/agrega.jpg"))); // NOI18N
        GUARDAR.setText("GUARDAR ");
        GUARDAR.setToolTipText("Guardar Registros");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(GUARDAR);
        GUARDAR.setBounds(430, 190, 150, 50);

        MODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/modificar1.jpg"))); // NOI18N
        MODIFICAR.setText("MODIFICAR ");
        MODIFICAR.setToolTipText("Modificar un registro existente");
        getContentPane().add(MODIFICAR);
        MODIFICAR.setBounds(430, 240, 150, 50);

        VER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/ver.jpg"))); // NOI18N
        VER.setText("VER ");
        VER.setToolTipText("Consultar Datos Existentes");
        VER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERActionPerformed(evt);
            }
        });
        getContentPane().add(VER);
        VER.setBounds(430, 90, 150, 50);

        SALIR.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aurelia\\Desktop\\SystemSolution\\src\\imagen2\\salir2.jpg")); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR);
        SALIR.setBounds(430, 390, 150, 50);

        jLabel7.setText("Marca");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 140, 60, 40);

        ComboTipoEquipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        ComboTipoEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboTipoEquipoMouseClicked(evt);
            }
        });
        ComboTipoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboTipoEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboTipoEquipo);
        ComboTipoEquipo.setBounds(100, 190, 190, 30);

        BotonAgregarNacionalidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonAgregarNacionalidad.setText("...");
        BotonAgregarNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNacionalidadActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarNacionalidad);
        BotonAgregarNacionalidad.setBounds(300, 190, 40, 30);

        ComboMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sleleccione..." }));
        ComboMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboMarca);
        ComboMarca.setBounds(100, 150, 190, 30);

        BotonAgregarBarrio.setText("...");
        BotonAgregarBarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarBarrioActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarBarrio);
        BotonAgregarBarrio.setBounds(300, 150, 40, 30);

        jLabel10.setText("Tipo Equipo");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 190, 90, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("EQUIPO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 20, 220, 30);

        jLabel11.setText("Medida");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 220, 50, 40);

        ComboMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        ComboMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboMedidaMouseClicked(evt);
            }
        });
        ComboMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMedidaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboMedida);
        ComboMedida.setBounds(100, 230, 200, 30);

        BotonAgregarNacionalidad1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonAgregarNacionalidad1.setText("...");
        BotonAgregarNacionalidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNacionalidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarNacionalidad1);
        BotonAgregarNacionalidad1.setBounds(310, 230, 40, 30);

        jLabel12.setText("Color");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 260, 70, 40);

        ComboColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        ComboColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboColorMouseClicked(evt);
            }
        });
        ComboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboColorActionPerformed(evt);
            }
        });
        getContentPane().add(ComboColor);
        ComboColor.setBounds(100, 270, 200, 30);

        BotonAgregarNacionalidad2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonAgregarNacionalidad2.setText("...");
        BotonAgregarNacionalidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNacionalidad2ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarNacionalidad2);
        BotonAgregarNacionalidad2.setBounds(310, 270, 40, 30);

        jLabel13.setText("Modelo");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 300, 60, 40);

        ComboModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        ComboModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComboModeloMouseClicked(evt);
            }
        });
        ComboModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboModeloActionPerformed(evt);
            }
        });
        getContentPane().add(ComboModelo);
        ComboModelo.setBounds(100, 310, 200, 30);

        BotonAgregarNacionalidad3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BotonAgregarNacionalidad3.setText("...");
        BotonAgregarNacionalidad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNacionalidad3ActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarNacionalidad3);
        BotonAgregarNacionalidad3.setBounds(310, 310, 40, 31);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void ComboTipoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboTipoEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTipoEquipoActionPerformed

    private void BotonAgregarNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNacionalidadActionPerformed
         new CTipoEquipo(new VTipoEquipo()).iniciar ();
    }//GEN-LAST:event_BotonAgregarNacionalidadActionPerformed

    private void ComboTipoEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboTipoEquipoMouseClicked
        //  ComboNacionalidad.removeAllItems();
            //combo
          this.ComboTipoEquipo.setModel(this.modelo.getListaTiposEquipos());
    }//GEN-LAST:event_ComboTipoEquipoMouseClicked

    private void BotonAgregarBarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarBarrioActionPerformed
         new CMarca(new VMarca()).iniciar();
    }//GEN-LAST:event_BotonAgregarBarrioActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUEVOActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
          this.ComboMarca.setModel(this.modelo.getListaMarca());
            this.ComboTipoEquipo.setModel(this.modelo.getListaTiposEquipos());
    }//GEN-LAST:event_formWindowActivated

    private void ComboMedidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboMedidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMedidaMouseClicked

    private void ComboMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMedidaActionPerformed

    private void BotonAgregarNacionalidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNacionalidad1ActionPerformed
        new CMedida(new VMedida()).iniciar();
    }//GEN-LAST:event_BotonAgregarNacionalidad1ActionPerformed

    private void ComboColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboColorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboColorMouseClicked

    private void ComboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboColorActionPerformed

    private void BotonAgregarNacionalidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNacionalidad2ActionPerformed
        new CColor(new VColor()).iniciar();
    }//GEN-LAST:event_BotonAgregarNacionalidad2ActionPerformed

    private void ComboModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComboModeloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboModeloMouseClicked

    private void ComboModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboModeloActionPerformed

    private void BotonAgregarNacionalidad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNacionalidad3ActionPerformed
         new CModelo(new VModelo()).iniciar ();
    }//GEN-LAST:event_BotonAgregarNacionalidad3ActionPerformed

    private void CampoDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDescripcionActionPerformed

    private void VERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VERActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GUARDARActionPerformed

    private void ComboMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMarcaActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAgregarBarrio;
    private javax.swing.JButton BotonAgregarNacionalidad;
    private javax.swing.JButton BotonAgregarNacionalidad1;
    private javax.swing.JButton BotonAgregarNacionalidad2;
    private javax.swing.JButton BotonAgregarNacionalidad3;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField CampoDescripcion;
    public javax.swing.JComboBox ComboColor;
    public javax.swing.JComboBox ComboMarca;
    public javax.swing.JComboBox ComboMedida;
    public javax.swing.JComboBox ComboModelo;
    public javax.swing.JComboBox ComboTipoEquipo;
    public javax.swing.JButton ELIMINAR;
    public javax.swing.JButton GUARDAR;
    public javax.swing.JButton IMPRIMIR;
    public javax.swing.JButton MODIFICAR;
    public javax.swing.JButton NUEVO;
    public javax.swing.JButton SALIR;
    public javax.swing.JButton VER;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
