/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Vista;



import Controlador.CFacturaVenta;
import Modelo.MAcceso;
import Modelo.MFacturaVenta;
import javax.swing.JOptionPane;


public class VFacturaVenta extends javax.swing.JFrame {
   
   MAcceso modeloAcceso = new MAcceso();
    
   public String cli = "";
    public String st = "";
MFacturaVenta modelo= new MFacturaVenta();
    /** Creates new form VFactVentas */
    public VFacturaVenta() {
        initComponents();
         CFacturaVenta mm=new CFacturaVenta(this);
         //*********************************************
          this.CampoCodigoUsuario.setText(modeloAcceso.xCodUsuario);
          this.CampoNombreUsuario.setText(modeloAcceso.xNombreUsuario);
           //*********************************************
        mm.limpiar();
       mm.iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoNro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboCliente = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        ComboTimbrado = new javax.swing.JComboBox();
        CampoNombreUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoCodigoUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CampoTotal = new javax.swing.JTextField();
        BotonAgregar_Detalle = new javax.swing.JButton();
        BotonEliminar_Detalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        ComboProducto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        CampoCantidad = new javax.swing.JTextField();
        CampoStock = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BotonAgregarVenta = new javax.swing.JButton();
        BotonGuardarVenta = new javax.swing.JButton();
        BotonCancelarVenta = new javax.swing.JButton();
        BotonSalirVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE VENTAS");
        setMinimumSize(new java.awt.Dimension(702, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setText("Numero");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 20);
        jPanel1.add(CampoNro);
        CampoNro.setBounds(60, 10, 70, 30);

        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 10, 70, 20);
        jPanel1.add(CampoFecha);
        CampoFecha.setBounds(570, 10, 90, 30);

        jLabel3.setText("Cliente:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 80, 20);

        ComboCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboClienteItemStateChanged(evt);
            }
        });
        jPanel1.add(ComboCliente);
        ComboCliente.setBounds(60, 60, 190, 30);

        jLabel8.setText("Timbrado");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 10, 80, 20);

        ComboTimbrado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboTimbradoItemStateChanged(evt);
            }
        });
        jPanel1.add(ComboTimbrado);
        ComboTimbrado.setBounds(230, 10, 160, 30);
        jPanel1.add(CampoNombreUsuario);
        CampoNombreUsuario.setBounds(380, 60, 140, 30);

        jLabel9.setText("Usuario");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(300, 60, 80, 20);
        jPanel1.add(CampoCodigoUsuario);
        CampoCodigoUsuario.setBounds(350, 60, 30, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 680, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        jLabel6.setText("Total:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(350, 250, 60, 20);
        jPanel2.add(CampoTotal);
        CampoTotal.setBounds(420, 240, 100, 30);

        BotonAgregar_Detalle.setText("Agregar Detalle");
        jPanel2.add(BotonAgregar_Detalle);
        BotonAgregar_Detalle.setBounds(540, 80, 130, 50);

        BotonEliminar_Detalle.setText("Eliminar Detalle");
        jPanel2.add(BotonEliminar_Detalle);
        BotonEliminar_Detalle.setBounds(540, 140, 130, 50);

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 520, 162);

        jLabel4.setText("Item");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 30, 70, 20);

        ComboProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboProductoItemStateChanged(evt);
            }
        });
        ComboProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboProductoActionPerformed(evt);
            }
        });
        jPanel2.add(ComboProducto);
        ComboProducto.setBounds(70, 20, 291, 30);

        jLabel5.setText("Cantidad");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(510, 30, 70, 20);
        jPanel2.add(CampoCantidad);
        CampoCantidad.setBounds(560, 20, 100, 30);

        CampoStock.setEnabled(false);
        jPanel2.add(CampoStock);
        CampoStock.setBounds(430, 20, 50, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 130, 680, 280);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(null);

        BotonAgregarVenta.setText("Agregar");
        jPanel3.add(BotonAgregarVenta);
        BotonAgregarVenta.setBounds(50, 10, 140, 70);

        BotonGuardarVenta.setText("Grabar");
        BotonGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(BotonGuardarVenta);
        BotonGuardarVenta.setBounds(190, 10, 140, 70);

        BotonCancelarVenta.setText("Cancelar");
        BotonCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(BotonCancelarVenta);
        BotonCancelarVenta.setBounds(330, 10, 140, 70);

        BotonSalirVenta.setText("Salir");
        BotonSalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirVentaActionPerformed(evt);
            }
        });
        jPanel3.add(BotonSalirVenta);
        BotonSalirVenta.setBounds(470, 10, 140, 70);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 420, 680, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarVentaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_BotonCancelarVentaActionPerformed

    private void BotonSalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirVentaActionPerformed
         int r=JOptionPane.showConfirmDialog(null,"Esta Seguro?");if(r==0){dispose();}
    }//GEN-LAST:event_BotonSalirVentaActionPerformed

    private void BotonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarVentaActionPerformed

    private void ComboClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboClienteItemStateChanged
//       String Combo[]=this.ComboCliente.getSelectedItem().toString().split("-");
//       cli=Combo[1].trim();
//     //  this.CampoNombreCliente.setText(cli);
    }//GEN-LAST:event_ComboClienteItemStateChanged

    private void ComboProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboProductoItemStateChanged
//       String Combo1[]=this.ComboProducto.getSelectedItem().toString().split("-");
//       st=Combo1[4].trim();
//       this.CampoStock.setText(st);
    }//GEN-LAST:event_ComboProductoItemStateChanged

    private void ComboTimbradoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboTimbradoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboTimbradoItemStateChanged

    private void ComboProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboProductoActionPerformed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VFacturaVenta().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAgregarVenta;
    public javax.swing.JButton BotonAgregar_Detalle;
    public javax.swing.JButton BotonCancelarVenta;
    public javax.swing.JButton BotonEliminar_Detalle;
    public javax.swing.JButton BotonGuardarVenta;
    public javax.swing.JButton BotonSalirVenta;
    public javax.swing.JTextField CampoCantidad;
    public javax.swing.JTextField CampoCodigoUsuario;
    public javax.swing.JTextField CampoFecha;
    public javax.swing.JTextField CampoNombreUsuario;
    public javax.swing.JTextField CampoNro;
    public javax.swing.JTextField CampoStock;
    public javax.swing.JTextField CampoTotal;
    public javax.swing.JComboBox ComboCliente;
    public javax.swing.JComboBox ComboProducto;
    public javax.swing.JComboBox ComboTimbrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaventas;
    // End of variables declaration//GEN-END:variables

}
