/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Vista;


import Controlador.CFactNotaCred;
import Controlador.CFactNotaDebito;
import Modelo.MAcceso;

import javax.swing.JOptionPane;

public class VFactNotaDebito extends javax.swing.JFrame {
MAcceso modeloAcceso = new MAcceso();
    /** Creates new form VFactVentas */
    public VFactNotaDebito() {
        initComponents();
         this.CampoCodUsuario.setText(modeloAcceso.xCodUsuario);
        this.CampoNombreUsuario.setText(modeloAcceso.xNombreUsuario);
        CFactNotaDebito mm=new CFactNotaDebito(this);
        mm.limpiar();
       mm.iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mFacturaCompra1 = new Modelo.MFacturaCompra();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodfact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        ComboFactura = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CampoCodUsuario = new javax.swing.JTextField();
        CampoNombreUsuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnagregar_detalle = new javax.swing.JButton();
        btneliminar_detalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cboInsumos = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        AgregarVenta = new javax.swing.JButton();
        GuardarVenta = new javax.swing.JButton();
        CancelarVenta = new javax.swing.JButton();
        SalirVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOTA DE DEBITO");
        setMinimumSize(new java.awt.Dimension(702, 520));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setText("Num Nota de debito");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 120, 30);

        txtcodfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodfactActionPerformed(evt);
            }
        });
        jPanel1.add(txtcodfact);
        txtcodfact.setBounds(130, 10, 160, 30);

        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 120, 40, 14);
        jPanel1.add(txtfecha);
        txtfecha.setBounds(80, 110, 140, 30);

        jLabel3.setText("Proveedor");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 80, 30);

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(comboProveedor);
        comboProveedor.setBounds(80, 150, 290, 30);

        jLabel9.setText("Num Factura Original");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 60, 110, 30);

        ComboFactura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ComboFactura);
        ComboFactura.setBounds(130, 60, 140, 30);

        jLabel7.setText("NOTA DE DEBITO ");
        jLabel7.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(580, 0, 110, 40);

        jLabel8.setText("Usuario");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 20, 40, 14);

        CampoCodUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CampoCodUsuario);
        CampoCodUsuario.setBounds(370, 10, 30, 30);

        CampoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CampoNombreUsuario);
        CampoNombreUsuario.setBounds(400, 10, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 700, 190);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        jLabel6.setText("TOTAL");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(350, 270, 60, 20);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotal);
        txtTotal.setBounds(430, 260, 100, 30);

        btnagregar_detalle.setText("Agregar Detalle");
        btnagregar_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar_detalleActionPerformed(evt);
            }
        });
        jPanel2.add(btnagregar_detalle);
        btnagregar_detalle.setBounds(540, 80, 120, 40);

        btneliminar_detalle.setText("Eliminar Detalle");
        jPanel2.add(btneliminar_detalle);
        btneliminar_detalle.setBounds(540, 140, 120, 40);

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nro", "Descripción", "Cantidad", "Precio ", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 520, 162);

        jLabel4.setText("Insumos");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 20, 70, 14);

        cboInsumos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cboInsumos);
        cboInsumos.setBounds(70, 10, 200, 30);

        jLabel5.setText("Cantidad");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 50, 70, 20);
        jPanel2.add(txtcantidad);
        txtcantidad.setBounds(70, 50, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 200, 700, 300);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(null);

        AgregarVenta.setText("Agregar");
        jPanel3.add(AgregarVenta);
        AgregarVenta.setBounds(30, 20, 100, 40);

        GuardarVenta.setText("Guardar");
        GuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(GuardarVenta);
        GuardarVenta.setBounds(170, 20, 100, 40);

        CancelarVenta.setText("Cancelar");
        CancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(CancelarVenta);
        CancelarVenta.setBounds(310, 20, 100, 40);

        SalirVenta.setText("Salir");
        SalirVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVentaActionPerformed(evt);
            }
        });
        jPanel3.add(SalirVenta);
        SalirVenta.setBounds(450, 20, 100, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 510, 690, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarVentaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CancelarVentaActionPerformed

    private void SalirVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVentaActionPerformed
         int r=JOptionPane.showConfirmDialog(null,"Esta Seguro?");if(r==0){dispose();}
    }//GEN-LAST:event_SalirVentaActionPerformed

    private void GuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarVentaActionPerformed

    private void btnagregar_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar_detalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregar_detalleActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtcodfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodfactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodfactActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void comboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboProveedorActionPerformed

    private void CampoCodUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodUsuarioActionPerformed

    private void CampoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreUsuarioActionPerformed

    
   // * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CFactNotaDebito(new VFactNotaDebito()).iniciar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AgregarVenta;
    public javax.swing.JTextField CampoCodUsuario;
    public javax.swing.JTextField CampoNombreUsuario;
    public javax.swing.JButton CancelarVenta;
    public javax.swing.JComboBox ComboFactura;
    public javax.swing.JButton GuardarVenta;
    public javax.swing.JButton SalirVenta;
    public javax.swing.JButton btnagregar_detalle;
    public javax.swing.JButton btneliminar_detalle;
    public javax.swing.JComboBox cboInsumos;
    public javax.swing.JComboBox comboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.MFacturaCompra mFacturaCompra1;
    public javax.swing.JTable tablaventas;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtcantidad;
    public javax.swing.JTextField txtcodfact;
    public javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables

}
