/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package Vista;


import Controlador.CFacturaCompra;
import Controlador.CPresupuesto;
import Modelo.MAcceso;

public class VPresupuesto extends javax.swing.JFrame {
MAcceso modeloAcceso = new MAcceso();
    /** Creates new form VFactVentas */
    public VPresupuesto() {
        initComponents();
        this.CampoCodUsuario1.setText(modeloAcceso.xCodUsuario);
        this.CampoNombreUsuario.setText(modeloAcceso.xNombreUsuario);
        CPresupuesto mm=new CPresupuesto(this);
        mm.limpiar();
       mm.iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPresupuesto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboFuncionario = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        ComboRecepcion = new javax.swing.JComboBox();
        txtfecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CampoNombreUsuario = new javax.swing.JTextField();
        CampoCodUsuario1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        agregarDetalle = new javax.swing.JButton();
        eliminarDetalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaventas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        comboServicios = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Agregar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOTA DE PRESUPUESTO");
        setMaximumSize(new java.awt.Dimension(850, 600));
        setMinimumSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setText("Codigo Presupuesto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 160, 30);

        txtPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPresupuestoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPresupuesto);
        txtPresupuesto.setBounds(160, 10, 100, 30);

        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(590, 20, 40, 20);

        jLabel3.setText("Funcionario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 80, 30);

        jPanel1.add(comboFuncionario);
        comboFuncionario.setBounds(110, 80, 160, 30);

        jLabel9.setText("Recepcion");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 80, 80, 30);

        jPanel1.add(ComboRecepcion);
        ComboRecepcion.setBounds(440, 80, 210, 30);
        jPanel1.add(txtfecha);
        txtfecha.setBounds(640, 10, 90, 30);

        jLabel8.setText("Usuario");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(330, 20, 60, 20);

        CampoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(CampoNombreUsuario);
        CampoNombreUsuario.setBounds(430, 10, 130, 30);

        CampoCodUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodUsuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(CampoCodUsuario1);
        CampoCodUsuario1.setBounds(390, 10, 30, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 120);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        jLabel6.setText("TOTAL");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(350, 250, 60, 20);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtTotal);
        txtTotal.setBounds(430, 240, 100, 30);

        agregarDetalle.setText("Agregar Detalle");
        agregarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDetalleActionPerformed(evt);
            }
        });
        jPanel2.add(agregarDetalle);
        agregarDetalle.setBounds(540, 80, 130, 50);

        eliminarDetalle.setText("Eliminar Detalle");
        jPanel2.add(eliminarDetalle);
        eliminarDetalle.setBounds(540, 140, 130, 50);

        tablaventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nro", "Descripción", "Cantidad", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tablaventas);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 520, 162);

        jLabel4.setText("Tipo Servicios");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 24, 70, 20);

        jPanel2.add(comboServicios);
        comboServicios.setBounds(90, 20, 210, 30);

        jLabel5.setText("Cantidad");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(380, 20, 70, 20);
        jPanel2.add(txtcantidad);
        txtcantidad.setBounds(460, 10, 100, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 130, 770, 280);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(null);

        Agregar.setText("Agregar");
        jPanel3.add(Agregar);
        Agregar.setBounds(30, 10, 110, 50);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel3.add(Guardar);
        Guardar.setBounds(170, 10, 110, 50);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel3.add(Cancelar);
        Cancelar.setBounds(310, 10, 110, 50);

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel3.add(Salir);
        Salir.setBounds(450, 10, 110, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 420, 770, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CancelarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
         {dispose();}
    }//GEN-LAST:event_SalirActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void agregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDetalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarDetalleActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPresupuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPresupuestoActionPerformed

    private void CampoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNombreUsuarioActionPerformed

    private void CampoCodUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodUsuario1ActionPerformed

    
   // * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPresupuesto(new VPresupuesto()).iniciar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Agregar;
    public javax.swing.JTextField CampoCodUsuario1;
    public javax.swing.JTextField CampoNombreUsuario;
    public javax.swing.JButton Cancelar;
    public javax.swing.JComboBox ComboRecepcion;
    public javax.swing.JButton Guardar;
    public javax.swing.JButton Salir;
    public javax.swing.JButton agregarDetalle;
    public javax.swing.JComboBox comboFuncionario;
    public javax.swing.JComboBox comboServicios;
    public javax.swing.JButton eliminarDetalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaventas;
    public javax.swing.JTextField txtPresupuesto;
    public javax.swing.JTextField txtTotal;
    public javax.swing.JTextField txtcantidad;
    public javax.swing.JTextField txtfecha;
    // End of variables declaration//GEN-END:variables

}
