/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CBarrio;
import Controlador.CNacionalidad;
import Modelo.MCliente;
import Modelo.MProveedor;





/**
 *
 * @author Teresa
 */
public class VProveedor extends javax.swing.JFrame {
     
    /**
     * Creates new form VProducto
     */
    public VProveedor() {
        initComponents();
    }
    MProveedor modelo = new MProveedor();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoRazonSocial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoRuc = new javax.swing.JTextField();
        ELIMINAR = new javax.swing.JButton();
        NUEVO = new javax.swing.JButton();
        IMPRIMIR = new javax.swing.JButton();
        GUARDAR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        VER = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CampoTelefono = new javax.swing.JTextField();
        SALIR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ComboBarrio = new javax.swing.JComboBox();
        BotonAgregarPais = new javax.swing.JButton();
        CampoDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Título 5", "Título 6", "Título 7"
            }
        ));
        tablaConsulta.setToolTipText("Consulta de Registros Existentes");
        tablaConsulta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaConsulta.setName(""); // NOI18N
        jScrollPane1.setViewportView(tablaConsulta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 740, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Consulta proveedor:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 340, 220, 30);

        jLabel3.setText("Codigo:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 120, 50, 20);

        CampoCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoCodigo);
        CampoCodigo.setBounds(120, 120, 70, 30);

        jLabel4.setText("Razon_Social");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 80, 20);

        CampoRazonSocial.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(CampoRazonSocial);
        CampoRazonSocial.setBounds(120, 160, 190, 30);

        jLabel5.setText("Ruc");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 240, 80, 30);

        CampoRuc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(CampoRuc);
        CampoRuc.setBounds(120, 240, 200, 30);

        ELIMINAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/eliminar.jpg"))); // NOI18N
        ELIMINAR.setText("ELIMINAR ");
        ELIMINAR.setToolTipText("Eliminar un registro existente");
        getContentPane().add(ELIMINAR);
        ELIMINAR.setBounds(790, 280, 180, 60);

        NUEVO.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aurelia\\Desktop\\SystemSolution\\src\\imagen2\\nuevoReg.jpg")); // NOI18N
        NUEVO.setText("NUEVO ");
        NUEVO.setToolTipText("Cancelar Operacion");
        NUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUEVOActionPerformed(evt);
            }
        });
        getContentPane().add(NUEVO);
        NUEVO.setBounds(790, 100, 180, 60);

        IMPRIMIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/imprimir.jpg"))); // NOI18N
        IMPRIMIR.setText("IMPRIMIR  ");
        IMPRIMIR.setToolTipText("Imprimir Listado");
        getContentPane().add(IMPRIMIR);
        IMPRIMIR.setBounds(790, 340, 180, 60);

        GUARDAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/agrega.jpg"))); // NOI18N
        GUARDAR.setText("GUARDAR ");
        GUARDAR.setToolTipText("Guardar Registros");
        getContentPane().add(GUARDAR);
        GUARDAR.setBounds(790, 160, 180, 60);

        MODIFICAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/modificar1.jpg"))); // NOI18N
        MODIFICAR.setText("MODIFICAR  ");
        MODIFICAR.setToolTipText("Modificar un registro existente");
        getContentPane().add(MODIFICAR);
        MODIFICAR.setBounds(790, 220, 180, 60);

        VER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/ver.jpg"))); // NOI18N
        VER.setText("VER ");
        VER.setToolTipText("Consultar Datos Existentes");
        getContentPane().add(VER);
        VER.setBounds(790, 40, 180, 60);

        jLabel9.setText("Telefono");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 280, 80, 30);

        CampoTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoTelefono);
        CampoTelefono.setBounds(120, 280, 200, 30);

        SALIR.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aurelia\\Desktop\\SystemSolution\\src\\imagen2\\salir2.jpg")); // NOI18N
        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR);
        SALIR.setBounds(790, 400, 180, 60);

        jLabel7.setText("Barrio");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 160, 60, 40);

        ComboBarrio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sleleccione..." }));
        getContentPane().add(ComboBarrio);
        ComboBarrio.setBounds(410, 160, 190, 30);

        BotonAgregarPais.setText("...");
        BotonAgregarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarPaisActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarPais);
        BotonAgregarPais.setBounds(610, 160, 45, 30);

        CampoDireccion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(CampoDireccion);
        CampoDireccion.setBounds(120, 200, 200, 30);

        jLabel11.setText("Direccion");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 200, 80, 30);

        CampoEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        CampoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailActionPerformed(evt);
            }
        });
        getContentPane().add(CampoEmail);
        CampoEmail.setBounds(400, 120, 180, 30);

        jLabel13.setText("Email");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(370, 120, 30, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText(" Proveedores:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 10, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodigoActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void BotonAgregarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarPaisActionPerformed
          new CBarrio(new VBarrio()) . iniciar ();
    }//GEN-LAST:event_BotonAgregarPaisActionPerformed

    private void NUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUEVOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUEVOActionPerformed

    private void CampoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefonoActionPerformed

    private void CampoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoDireccionActionPerformed

    private void CampoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
          this.ComboBarrio.setModel(this.modelo.getListaBarrio());
    }//GEN-LAST:event_formWindowActivated

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BotonAgregarPais;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField CampoDireccion;
    public javax.swing.JTextField CampoEmail;
    public javax.swing.JTextField CampoRazonSocial;
    public javax.swing.JTextField CampoRuc;
    public javax.swing.JTextField CampoTelefono;
    public javax.swing.JComboBox ComboBarrio;
    public javax.swing.JButton ELIMINAR;
    public javax.swing.JButton GUARDAR;
    public javax.swing.JButton IMPRIMIR;
    public javax.swing.JButton MODIFICAR;
    public javax.swing.JButton NUEVO;
    public javax.swing.JButton SALIR;
    public javax.swing.JButton VER;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
